In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
dataset = pd.read_csv("Placement.csv")

In [4]:
#dataset

In [5]:
#Separating quantitative data and qualitative data using a function written in the class Univariate

In [6]:
from Univariate import Univariate
quan, qual = Univariate.QuanQual(dataset)
print("quan", quan)
print("qual", qual)

quan ['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary']
qual ['gender', 'ssc_b', 'hsc_b', 'hsc_s', 'degree_t', 'workex', 'specialisation', 'status']

In [7]:
#Univariate.FreqTable("hsc_p", dataset)

In [8]:
#  Viewing the Descriptive table using the function written in Univariate class
descriptive = Univariate.univariate(dataset, quan)

In [9]:
descriptive

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0
Q1:25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
Q2:50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Q3:75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
99%,212.86,87.0,91.86,83.86,97.0,76.1142,NaN
Q4:100%,215.0,89.4,97.7,91.0,98.0,77.89,940000.0
IQR,107.0,15.1,12.1,11.0,23.5,8.31,60000.0
1.5Rule,160.5,22.65,18.15,16.5,35.25,12.465,90000.0
Lesser,-106.0,37.95,42.75,44.5,24.75,45.48,150000.0
Greater,322.0,98.35,91.15,88.5,118.75,78.72,390000.0
Min,1,40.89,37.0,50.0,50.0,51.21,200000.0
Max,215,89.4,97.7,91.0,98.0,77.89,940000.0
kurtosis,-1.2,-0.60751,0.450765,0.052143,-1.08858,-0.470723,18.544273
skew,0.0,-0.132649,0.163639,0.244917,0.282308,0.313576,3.569747
var,3870.0,117.228377,118.755706,54.151103,176.251018,34.028376,8734295412.759695
stddev,62.209324,10.827205,10.897509,7.358743,13.275956,5.833385,93457.45242

In [10]:
# 3. Find outliers using a function written in the class
#lesser, greater = Univariate.Finding_outliers(descriptive, quan)

In [11]:
# 4. Display result
#print("Lesser Outliers:", lesser)
#print("Greater Outliers:", greater)

In [12]:
# Replace outliers using a function written in the class
#Univariate.Handle_outliers(dataset, descriptive, quan)

In [13]:
# 3. Checking if outliers exist after replacing outliers
#lesser, greater = Univariate.Finding_outliers(descriptive, quan)

In [14]:
# 4. Display result
#print("Lesser Outliers:", lesser)
#print("Greater Outliers:", greater)

In [15]:
#print(dataset["hsc_p"].min())
#print(descriptive["hsc_p"]["Lesser"])
#print(dataset["hsc_p"].max())
#print(descriptive["hsc_p"]["Greater"])
#print(dataset["degree_p"].max())
#print(descriptive["degree_p"]["Greater"])
#print(dataset["salary"].max())
#print(descriptive["salary"]["Greater"])

In [16]:

# 3. Find outliers
lesser, greater = Univariate.Finding_outliers(descriptive, quan)

print("Before Handling")
print("Lesser:", lesser)
print("Greater:", greater)

# 4. Handle/replace outliers
dataset = Univariate.Handle_outliers(dataset, descriptive, quan)

# 5. Recalculate descriptive statistics, dataframe table with replaced values
descriptive = Univariate.univariate(dataset, quan)

# 6. Check outliers again
lesser, greater = Univariate.Finding_outliers(descriptive, quan)

print("\nAfter Handling")
print("Lesser:", lesser)
print("Greater:", greater)
descriptive

Before Handling
Lesser: ['hsc_p']
Greater: ['hsc_p', 'degree_p', 'salary']

After Handling
Lesser: []
Greater: []

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.334744,66.358558,72.100558,62.278186,277648.648649
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0
Q1:25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
Q2:50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Q3:75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
99%,212.86,87.0,91.129,83.86,97.0,76.1142,NaN
Q4:100%,215.0,89.4,91.15,88.5,98.0,77.89,390000.0
IQR,107.0,15.1,12.1,11.0,23.5,8.31,60000.0
1.5Rule,160.5,22.65,18.15,16.5,35.25,12.465,90000.0
Lesser,-106.0,37.95,42.75,44.5,24.75,45.48,150000.0
Greater,322.0,98.35,91.15,88.5,118.75,78.72,390000.0
Min,1,40.89,42.75,50.0,50.0,51.21,200000.0
Max,215,89.4,91.15,88.5,98.0,77.89,390000.0
kurtosis,-1.2,-0.60751,0.086901,-0.09749,-1.08858,-0.470723,-0.239837
skew,0.0,-0.132649,0.162611,0.204164,0.282308,0.313576,0.8067
var,3870.0,117.228377,112.063731,53.60471,176.251018,34.028376,2944596800.882515
stddev,62.209324,10.827205,10.586016,7.321524,13.275956,5.833385,54264.139179

In [18]:
#Finding Frequency information for a column; using a function in the written class
Univariate.FreqTable("hsc_p", dataset)

    Unique_values  Frequency  Relative Frequency    Cumsum
0           63.00        NaN                 NaN       NaN
1           62.00        NaN                 NaN       NaN
2           60.00        NaN                 NaN       NaN
3           67.00        NaN                 NaN       NaN
4           70.00        NaN                 NaN       NaN
..            ...        ...                 ...       ...
86          70.29        1.0            0.004651  0.688372
87          83.83        2.0            0.009302  0.697674
88          70.40        NaN                 NaN       NaN
89          90.90        NaN                 NaN       NaN
90          61.33        2.0            0.009302  0.706977

[91 rows x 4 columns]